KB_DOCS = [
    {"id": "shipping_times",
        "text": "Standard delivery takes 3–5 business days within major cities and 5–8 business days for other locations. Express delivery (1–2 business days) is available at checkout for an additional fee. Orders placed before 2pm ship the same day."},
    {"id": "shipping_costs", "text": "Standard shipping is free on orders over ₦50,000. Orders below that threshold have a flat ₦2,500 shipping fee. Express shipping is calculated at checkout based on weight and destination."},
    {"id": "returns", "text": "Items can be returned within 14 days of delivery if unused, in original packaging, with proof of purchase. Perishable items and opened personal-care products are not eligible for return."},
    {"id": "refunds", "text": "Once a return is received and inspected, refunds are processed within 5–7 business days to the original payment method. You'll get an email confirmation when the refund is issued."},
    {"id": "tracking", "text": "A tracking link is emailed automatically once an order ships. Tracking can also be checked by logging into your account under 'My Orders.'"},
    {"id": "payment", "text": "We accept debit/credit cards, bank transfer, and major mobile payment wallets. Payment is processed securely at checkout; we never store full card details."},
    {"id": "warranty",
        "text": "All small appliances (blenders, kettles, toasters, etc.) come with a 12-month manufacturer warranty covering defects. Warranty claims require the original receipt and are handled through the manufacturer's service center."},
    {"id": "cookware_care", "text": "Non-stick cookware should be hand-washed with a soft sponge — no metal utensils or abrasive scrubbers, as these damage the coating. Avoid high heat above medium for non-stick pans to preserve the coating's lifespan."},
    {"id": "wholesale", "text": "For orders over 20 units of the same item, contact our sales team directly for wholesale pricing. Bulk orders typically ship within 7–10 business days depending on stock."},
    {"id": "damaged_item", "text": "If an item arrives damaged, contact support within 48 hours with photos of the damage and packaging. A replacement or full refund will be issued — no need to return the damaged item in most cases."},
    {"id": "cancellation", "text": "Orders can be cancelled free of charge within 1 hour of placing them. After that, the order may already be processing and cancellation isn't guaranteed — contact support immediately if this happens."},
    {"id": "gift_wrapping", "text": "Gift wrapping is available at checkout for a small fee and includes a printed gift note if you add a message. Gift cards are available in fixed denominations and don't expire."},
    {"id": "international", "text": "We currently ship only within the country. International shipping isn't available yet, but you can sign up for restock/expansion notifications on the homepage."},
    {"id": "pickup", "text": "Store pickup isn't currently offered — all orders are delivered directly to the address provided at checkout."},
    {"id": "escalation", "text": "If a question falls outside what I can answer, or you'd prefer to speak with a person directly, I'll flag it for the team and someone will follow up by email within one business day."},
]
